### ISSUE TITLE
VIDEOJS: WARN: Player is already initialised. Options will not be applied.

### ISSUE THREAD

**Issue by timokuehne** [hola/videojs5-hola-skin#1] opened 2016-07-15 11:12 UTC
Hi Norlin,

we really love your player design, but unfortunately with have two issues with it. I made a video for you for easy understanding our issues. I hope you can help us.

Here you can find the video -> https://www.videolyser.de/content/6126912/hola-skin

and here you can find the example site -> https://www.videolyser.de/vjs5.10.7/index.html

**Comment by norlin** [comment] 2016-07-15 11:33
Hi!

Thanks for such detailed issue :-)

I've checked the warning message, and it seems it happens because of Videojs initialization way:
As I see on the example page, you're using `data-setup={}` attribute AND javascript-init with `videojs(...)` at the same time.

Videojs code makes auto-init for vjs instance in case if `data-setup` attribute exists.
Please check this [vjs docs](http://docs.videojs.com/docs/guides/setup.html)

> Note: The data-setup attribute described here should not be used if you use the alternative setup described in the next section.

About second issue with BigPlayButton – as I see, you're using a pretty old skin build (v0.0.1-5).
Please check for the latest build in the [Tags](https://github.com/hola/videojs5-hola-skin/tags) section

For now, I will close this issue; if you will find those things not helps you – please don't hesitate to leave new comments here.

**Closed as completed by norlin** 2016-07-15 11:33 UTC

**Comment by timokuehne** [comment] 2016-07-19 17:06
Hi Norlin,

thanks for your help. I updated the scripts and removed the data-setup from the video tag. Now everything is fine.

I have another small problem now with the svg pause icon. If you click on my example video, switch to fullscreen and zoom with browser till 500%, then you see better what I mean. I made a stroke on the icons, but the left side of the pause icon have a problem. Can you help me or telling me what I can do? I have not much experience with svg. I tried to edit it with an svg editor, but there everything seems good. What I can do?

Here is my example video -> https://www.videolyser.de/video/6126912/800/450/

It will be really nice, if you can help us.

regards, Timo

**Comment by norlin** [comment] 2016-07-20 11:54
@timokuehne Hi!

Do you mean this issue? 
<img width="191" alt="pause_button" src="https://cloud.githubusercontent.com/assets/370803/16985534/2cf239f2-4e92-11e6-910a-61cd238cc0a0.png">

It could be a bug with svg icon or animation, not yet sure. We'll try to fix it, thank you!

**Comment by timokuehne** [comment] 2016-07-20 16:45
Yes, I mean excatly this issue.

**Comment by timokuehne** [comment] 2016-07-29 18:42
Hi norlin. I don't want annoy you, but can you help us with this problem?

**Comment by norlin** [comment] 2016-08-02 11:11
Hi @timokuehne!
Yes, we've added this into our plan, but I can't say anything about when this issue will be fixed.

**Comment by norlin** [comment] 2016-08-16 12:46
@timokuehne, could you please check [the latest version](https://github.com/hola/videojs5-hola-skin/releases/tag/v0.0.5-29)? should be no this graphic issue.
Also, I'm not sure why there is the black 1px stroke on your example's icons, supposed there is no stroke.

**Comment by timokuehne** [comment] 2016-08-16 17:18
Hi Norlin. I've tested a new clean installation of videojs + latest hola-skin. Nothing changes. Still the same problem. I changed a little bit the css in the browser to make it more visible.
![stroke](https://cloud.githubusercontent.com/assets/11676348/17708655/37bd03d0-63e6-11e6-9694-1d925988859a.png)

**Comment by norlin** [comment] 2016-08-17 10:51
@timokuehne so, the issue is there only when you're applying a black stroke?

**Comment by timokuehne** [comment] 2016-08-18 18:59
Yes, correct. But I need the black stroke, because some people are uploading videos with white backgrounds. Presentations for example. And without black stroke you can't see the control icons anymore. That's the reason.
